%YAML:1.0

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
# test.InitVIOTmpPath: "/home/jp/opensourcecode/OpenSourceORBVIO/tmp/"
test.InitVIOTmpPath: "/home/davidz/work/ros/indigo/src/vslam_node/ORB_VIO/results/"

# 1: realtime, 0: non-realtime
test.RealTime: 1
# Time for visual-inertial initialization
test.VINSInitTime: 15.0

## For good initialization (no movement at the beginning for some bag)
test.DiscardTime: 0
#bagfile: "/home/jp/TimeV1_01_easy.bag"
## bad: V1_03_difficult(wrong), V2_03_difficult(lost)
## not so good(cant close loop without loopclosure): V1_02_medium, V2_02_medium, MH_05_difficult
## good: V1_01_easy, V2_01_easy, MH_01_easy, MH_02_easy, MH_03_medium, MH_04_difficult

#test.DiscardTime: 18
#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_03_medium.bag"

#bagfile: "/media/jp/JingpangPassport/3dataset/EuRoC-VIO/un_restamped/MH_04_difficult.bag"
# bagfile: "/home/davidz/work/data/EuRoC-VIO/V2_02_medium.bag"
# bagfile: "/media/davidz/work/work/data/realsense/ETAS_2F_640_30.bag"
# bagfile: "/media/davidz/work/work/data/realsense/R200GT_dense_slow_640_06_30.bag"
# bagfile: "/media/davidz/work/work/data/realsense/etasF4_06_01_01"
# bagfile: "/home/davidz/work/data/ETAS_F2_640_30"
# bagfile: "/media/davidz/Seagate Backup Plus Drive/dataset/tum_vio/dataset-room1_512_16.bag"
# bagfile: "/media/davidz/Course/tum_vio/dataset-room4_512_16.bag"
bagfile: "/media/davidz/Seagate Backup Plus Drive/dataset/tum_vio/dataset-room2_512_16.bag"


#######################################

imutopic: "/imu0"
imagetopic: "/cam0/image_raw" #"/cam0/image_raw" /cam0/color

# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0 # -0.467116630307 

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
        [ -0.99953071, 0.00744168, -0.02971511,  0.04536566,  
           0.0294408, -0.3459565,  -0.99896766,   -0.071996,
          -0.00846201, -0.99937369, 0.03436032, -0.04478181, 
        0.0, 0.0, 0.0, 1.0]

# Local Window size
LocalMapping.LocalWindowSize: 20

# VINS Init Required Time
# LocalMapping.VINSInitTime: 15. # 15. # 9.

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 190.9785 # 615.426 # 458.654
Camera.fy: 190.9733 # 625.456 # 457.296
Camera.cx: 254.9317 # 318.837 # 367.215
Camera.cy: 256.8974 # 240.594 # 248.375

# D = [-0.284779809132009,0.0824505247648799, -1.09461560717260e-06,  ...
#    4.78701071508643e-06,-0.0104084647110111];

Camera.k1:  -0.239552  #-0.2847798 # -0.239552  # -0.2847798
Camera.k2: 0.037056  # 0.08245052 # 0.037056  # 0.08245052
Camera.p1: 3.5763956e-6 # -1.09461560717260e-06 # 3.5763956e-6  #  -1.09461560717260e-06,
Camera.p2: -1.4032145e-5 # 4.78701072e-6 # -1.4032145e-5 #   4.78701072e-6
Camera.k3: 0 # -0.0104085 # 0.            # -0.0104085

Camera.width:  512 # 640
Camera.height: 512 # 480

# Camera frames per second 
Camera.fps: 20.0 # 20.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid 
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast   
ORBextractor.iniThFAST: 20 # 20
ORBextractor.minThFAST: 7 # 7 

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

