%YAML:1.0

#common parameters 
#
# TODO: change these topics 
imu_topic: "/imu0"
# image_topic: "/cam0/color" # "/cam0/image_raw"
image_topic: "/camera/color/image_rect_color" # "/cam0/image_raw"
output_path: "/home/hzhang8/work/ros/kinetic/src/vslam_node/result"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.
   k2: 0.
   p1: 0.
   p2: 0.
projection_parameters: 
   fx: 617.306
   fy: 617.714
   cx: 326.245
   cy: 239.974

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0 #1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1, 0, 0, 
           0, 1, 0, 
           0, 0, 1]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   # data: [-0.02,-0.06, 0.01]
   # data: [0.063, -0.001, 0.018]
   data: [-0.01, 0, 0.025]

#feature traker paprameters
max_cnt: 150  # 150          # max feature number in feature tracking
min_dist: 20  # 30          # min distance between two features 
freq: 10 # 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 3.0 # 2.0 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # 1 if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # 0.04 max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # 8 max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# TODO: figure out these parameters
acc_n: 0.014           # accelerometer measurement noise standard deviation. #0.001372
gyr_n: 0.0006          # gyroscope measurement noise standard deviation.     #0.000061087
acc_w: 0.00277 # 0.000277          # accelerometer bias random work noise standard deviation.  #0.000027719
gyr_w: 0.0003428 # 0.00003428        # gyroscope bias random work noise standard deviation.     #0.000003428
g_norm: 9.81007     # gravity magnitude


pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 25

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/tony-ws1/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.000                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 1                      # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0.033               # unit: s. rolling shutter read out time per frame (from data sheet). 



