/pose_sensor/core/data_playback: true # true
/pose_sensor/core/fixed_bias: 0

#########IMU PARAMETERS#######
######## Vn100 IMU
/pose_sensor/core/core_noise_acc: 0.014
/pose_sensor/core/core_noise_accbias: 0.004 # x10
/pose_sensor/core/core_noise_gyr: 0.002
/pose_sensor/core/core_noise_gyrbias: 0.0005 # x10

######## Pose Sensor Parameters #########
/msf_svo/pose_sensor/pose_absolute_measurements: true
/msf_svo/pose_sensor/pose_measurement_world_sensor: false  # selects if sensor measures its position w.r.t. world (true, e.g. Vicon) or the position of the world coordinate system w.r.t. the sensor (false, e.g. ethzasl_ptam

/msf_svo/pose_sensor/pose_delay: 0.000
/msf_svo/pose_sensor/pose_measurement_minimum_dt: 0.05  # Sets the minimum time in seconds between two pose measurements.

/msf_svo/pose_sensor/pose_use_fixed_covariance: false
/msf_svo/pose_sensor/pose_noise_meas_p: 0.01              # [m]
/msf_svo/pose_sensor/pose_noise_meas_q: 0.02              # [rad]

# /msf_svo/pose_sensor/fixed_scale: 1
/msf_svo/pose_sensor/pose_initial_scale: 1
/msf_svo/pose_sensor/pose_fixed_scale: false
/msf_svo/pose_sensor/pose_noise_scale: 0.0
/msf_svo/pose_sensor/pose_noise_p_wv: 0.0
/msf_svo/pose_sensor/pose_noise_q_wv: 0.0
/msf_svo/pose_sensor/pose_noise_q_ic: 0.0
/msf_svo/pose_sensor/pose_noise_p_ic: 0.0

/msf_svo/pose_sensor/init/q_ic/w: 1.0
/msf_svo/pose_sensor/init/q_ic/x: 0.0
/msf_svo/pose_sensor/init/q_ic/y: 0.0
/msf_svo/pose_sensor/init/q_ic/z: 0.0
/msf_svo/pose_sensor/init/p_ic/x: 0.063   
/msf_svo/pose_sensor/init/p_ic/y: -0.001
/msf_svo/pose_sensor/init/p_ic/z: 0.018

/msf_svo/pose_sensor/pose_fixed_p_ic: true
/msf_svo/pose_sensor/pose_fixed_q_ic: true
/msf_svo/pose_sensor/pose_fixed_p_wv: true
/msf_svo/pose_sensor/pose_fixed_q_wv: true
 

